Ext.define("cn.article.view.ArticleGridView",{
	extend:"Ext.grid.Panel",
	alias:"widget.articleGridView",
	store:"cn.article.store.ArticleStore",
	multiSelect:true,
	selModel:Ext.create("Ext.selection.CheckboxModel"),
	selType:"cellmodel",
	plugins: [
		Ext.create('Ext.grid.plugin.CellEditing', { 
        clicksToEdit: 2
     })],
	frame:true,
	enableKeyNav:true,//可以用键盘控制上下
	columnLines:true,//展示竖线
	disableSelection:false, // 值为true表示禁止选择行
	//selModel:Ext.create("Ext.selection.CheckboxModel"),
	columns:[{
		xtype:"rownumberer"
	},{
		id:"title",
		text:"标题",
		width:110,
		dataIndex:"title",
		sortable:true,
		field:{
			allowBlank:false
		}
	},{
		text:"作者",
		width:120,
		dataIndex:"author",
		id:"author",
		sortable:false,
		field:{
			xtype:"combobox",
			id:"authors",
			typeAhead:true,
			triggerAction:"all",
			queryMode:"local",
			selectonOnTab:true,
			store:"",
			lazyRender:true,
			displayField:"",
			valueField:"",
			listClass:"x-combo-list-small"
		}
	},{
		text:"点击数",
		width:80,
		dataIndex:"clickNumber",
		sortable:true,
		field:{
			xtype:"numberfield",
			allowBlank:false,
			minValue:0,
			maxValue:10000
		}
	},{
		text:"出版时间",
		width:200,
		dataIndex:"publishTime",
		renderer:"",//此处还没有实现
		field:{
			xtype:"datefield",
			format:"Y-m-d",
			minValue:"01/01/06"
		}
	},{
		text:"出版地",
		width:100,
		dataIndex:"publishPlace",
	},{
		id:"auditingId",
		text:"审核",
		dataIndex:"auditing",
		width:55,
		field:{
			allowBlank:true
		}
	}],//columns
	initComponent:function(){
		this.callParent(arguments);
	}
});