document.writeln("<style>");
document.writeln("*{ margin:0; padding:0; list-style:none;}");
document.writeln("img{ border:0;}");
document.writeln(".main-im{ position:fixed; right:-2px; top:150px; z-index: 100; width: 110px; height: 272px; }");
document.writeln(".main-im .qq-a { display: block; width: 106px; height: 116px; font-size: 14px; color: #0484cd; text-align: center; position: relative; }");
document.writeln(".main-im .qq-a span { bottom: 5px; position: absolute; width: 90px; left: 10px; }");
document.writeln(".main-im .qq-hover-c { width: 70px; height: 70px; border-radius: 35px; position: absolute; left: 18px; top: 10px; overflow: hidden; z-index: 9; }");
document.writeln(".main-im .qq-container { z-index: 99; position: absolute; width: 109px; height: 118px; border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom: 1px solid #dddddd; background: url(http:\/\/www.educity.cn\/js\/images\/qq-icon-bg.png) no-repeat center 8px; }");
document.writeln(".main-im .img-qq {max-width: 60px; display: block; position: absolute; left: 6px; top: 3px; -moz-transition: all 0.5s; -webkit-transition: all 0.5s; -o-transition: all 0.5s; transition: all 0.5s; }");
document.writeln(".main-im .im-qq:hover .img-qq{ max-width: 70px; left: 1px; top: 8px; position: absolute; }");
document.writeln(".main-im .im_main {background: #F9FAFB; border: 1px solid #dddddd; border-radius: 10px; background: #F9FAFB;display:none;}");
document.writeln(".main-im .im_main .im-tel { color: #000000; text-align: center; width: 109px; height: 45px; border-bottom: 1px solid #dddddd; }");
document.writeln(".main-im .im_main .im-tel div{font-weight:bold;font-size: 12px;margin-top:11px;}");
document.writeln(".main-im .im_main .im-tel .tel-num { font-family: Arial; font-weight: bold; color: #e66d15;}");
document.writeln(".main-im .im_main .im-tel:hover { background: #fafafa; }");
document.writeln(".main-im .im_main .weixing-container {width: 55px; height: 47px; border-right: 1px solid #dddddd; background: #f5f5f5; border-bottom-left-radius: 10px; background: url(http:\/\/www.educity.cn\/js\/images\/weixing-icon.png) no-repeat center center;float:left;}");
document.writeln(".main-im .im_main .weixing-show {width: 115px; height: 170px; background: #ffffff; border-radius: 10px; border: 1px solid #dddddd; position: absolute; left: -125px; top: -126px; }");
document.writeln(".main-im .im_main .weixing-show .weixing-sanjiao {width:0; height: 0; border-style: solid; border-color: transparent transparent transparent #ffffff; border-width: 6px; left: 115px; top: 138px; position: absolute; z-index: 2;}");
document.writeln(".main-im .im_main .weixing-show .weixing-sanjiao-big { width: 0; height: 0; border-style: solid; border-color: transparent transparent transparent #dddddd; border-width: 8px; left: 115px; top: 136px; position: absolute; }");
document.writeln(".main-im .im_main .weixing-show .weixing-ma { width: 105px; height: 134px; padding-left: 5px; padding-top: 5px; }");
document.writeln(".main-im .im_main .weixing-show .weixing-txt{position:absolute;top:140px;left:7px;width:100px;margin:0 auto; text-align:center; font-size:12px;height:20px;line-height:20px}");
document.writeln(".main-im .im_main .go-top { width: 50px; height: 47px; background: #f5f5f5; border-bottom-right-radius: 10px; background: url(http:\/\/www.educity.cn\/js\/images\/toTop-icon.png) no-repeat center center;float:right;}");
document.writeln(".main-im .im_main .go-top a { display: block; width: 52px; height: 47px; }");
document.writeln(".main-im .close-im { position: absolute; right: 10px; top: -12px; z-index: 100; width: 24px; height: 24px; }");
document.writeln(".main-im .close-im a { display: block; width: 24px; height: 24px; background: url(http:\/\/www.educity.cn\/js\/images\/close_im.png) no-repeat left top; }");
document.writeln(".main-im .close-im a:hover { text-decoration: none; }");
document.writeln(".main-im .open-im { cursor: pointer; margin-left: 68px; width: 40px; height: 133px; background: url(http:\/\/www.educity.cn\/js\/images\/open_im.png) no-repeat left top; }");
document.writeln("<\/style>");
document.writeln("<div class=\"main-im\">");
document.writeln("  <div id=\"open_im\" class=\"open-im\"><\/div>  ");
document.writeln("  <div class=\"im_main\" id=\"im_main\">");
document.writeln("    <div id=\"close_im\" class=\"close-im\"><a href=\"javascript:void(0);\" title=\"点击关闭\"><\/a><\/div>");
document.writeln("    <a href=\"http:\/\/wpa.qq.com\/msgrd?v=3&uin=2318577953&site=qq&menu=yes\" class=\"im-qq qq-a\" title=\"在线QQ客服\">");
document.writeln("    <div class=\"qq-container\"><\/div>");
document.writeln("    <div class=\"qq-hover-c\"><img class=\"img-qq\" src=\"http:\/\/www.educity.cn\/js\/images\/qq.png\"><\/div>");
document.writeln("    <span> QQ在线咨询<\/span> <\/a>");
document.writeln("    <div class=\"im-tel\">");
document.writeln("      <div>免费咨询热线<\/div>");
document.writeln("      <div class=\"tel-num\">400-777-1218<\/div>");
document.writeln("    <\/div>");
document.writeln("    <div class=\"im-footer\" style=\"position:relative\">");
document.writeln("      <div class=\"weixing-container\">");
document.writeln("        <div class=\"weixing-show\">");
document.writeln("           <div class=\"weixing-txt\">获得更多惊喜<\/div>");
document.writeln("          <img class=\"weixing-ma\" src=\"http:\/\/www.educity.cn\/js\/weixin_pic.png\">");
document.writeln("          <div class=\"weixing-sanjiao\"><\/div>");
document.writeln("          <div class=\"weixing-sanjiao-big\"><\/div>");
document.writeln("        <\/div>");
document.writeln("      <\/div>");
document.writeln("      <div class=\"go-top\"><a href=\"javascript:;\" title=\"返回顶部\"><\/a> <\/div>");
document.writeln("	 <div style=\"clear:both\"><\/div>");
document.writeln("    <\/div>");
document.writeln("  <\/div>");
document.writeln("<\/div>");
document.writeln("<script src=\"http:\/\/www.educity.cn\/js\/jquery-1.7.min.js\"><\/script>");
document.writeln("<script>");
document.writeln("$(function(){");
document.writeln("	$(\'#close_im\').bind(\'click\',function(){");
document.writeln("		$(\'#main-im\').css(\"height\",\"0\");");
document.writeln("		$(\'#im_main\').hide();");
document.writeln("		$(\'#open_im\').show();");
document.writeln("	});");
document.writeln("	$(\'#open_im\').bind(\'click\',function(e){");
document.writeln("		$(\'#main-im\').css(\"height\",\"272\");");
document.writeln("		$(\'#im_main\').show();");
document.writeln("		$(this).hide();");
document.writeln("	});");
document.writeln("	$(\'.go-top\').bind(\'click\',function(){");
document.writeln("		$(window).scrollTop(0);");
document.writeln("	});");
document.writeln("	$(\".weixing-container\").bind(\'mouseenter\',function(){");
document.writeln("		$(\'.weixing-show\').show();");
document.writeln("	})");
document.writeln("	$(\".weixing-container\").bind(\'mouseleave\',function(){        ");
document.writeln("		$(\'.weixing-show\').hide();");
document.writeln("	});");
document.writeln("});");
document.writeln("<\/script>");