/*! ver:1426591083 Copyright 2015 Baidu Inc. All Rights Reserved. */;(function(){var l=void 0,n=!0,s=null,u=!1,E=window.BAIDU_DUP_require,H=window.BAIDU_DUP_define;
H&&H("union/common/bom1426591083",[],function(){var g={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(g.g=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Wc=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(g.jd=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Sc=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.dd)&&
(g.ed=+RegExp.$1)}catch(f){}g.Eb=/webkit/i.test(navigator.userAgent);g.sc=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);g.Db="CSS1Compat"==document.compatMode;return{h:g,A:function(){var e=n;if(this.h.g&&(7>this.h.g||"BackCompat"===document.compatMode))e=u;return e},Zc:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.scrollWidth:e.document.documentElement.scrollWidth}catch(f){return 0}},Yc:function(e){try{return e=e||window,"BackCompat"===
e.document.compatMode?e.document.body.scrollHeight:e.document.documentElement.scrollHeight}catch(f){return 0}},D:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientWidth:e.document.documentElement.clientWidth}catch(f){return 0}},o:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientHeight:e.document.documentElement.clientHeight}catch(f){return 0}},F:function(e){e=(e||window).document;return window.pageYOffset||e.documentElement.scrollTop||
e.body.scrollTop},$a:function(e){e=(e||window).document;return window.pageXOffset||e.documentElement.scrollLeft||e.body.scrollLeft},Fb:function(e){var f=u;try{e&&"object"===typeof e&&e.document&&"setInterval"in e&&(f=n)}catch(d){f=u}return f},pa:function(e){e=e||window;return e!=window.top&&e!=e.parent||!this.Fb(e)},Da:function(e,f){for(var f=2===arguments.length?f:e.parent,d=0;10>d++&&this.pa(e,f);){var i;try{i=!!e.parent.location.toString()}catch(c){i=u}if(!i)return n;e=e.parent}return 10<=d?n:
u},Dc:function(e,f){var d=new Image,i="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),f=f||window;f[i]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=s;d=f[i]=s};d.src=e},Ya:function(e){if(!e)return document;"string"===typeof e&&(e=document.getElementById(e));return 9===e.nodeType?e:e.ownerDocument||e.document},ab:function(e){"string"===typeof e&&(e=document.getElementById(e));e=this.Ya(e);return e.parentWindow||e.defaultView||s},ad:function(e){e=e||window;return this.pa(e)&&
!this.Da(e,e.top)&&this.Fb(e.top)?e.top:e}}});
H&&H("union/common/logic1426591083",[],function(){return{Uc:function(g){(g=g||"")&&(g=g.replace(/%u[\d|\w]{4}/g,function(f){return encodeURIComponent(unescape(f))}));return g},R:function(g,f){return g.replace(/{(.*?)}/g,function(e,g){return f[g]||""})},vc:function(g){return(new Function("return "+g))()},Bb:function(g,f){if(g&&f){var e=g.match(RegExp("(^|&|\\?|#)"+f+"=([^&]*)(&|$)",""));if(e)return e[2]}return s},gd:function(g,f){var g=g||"",f=f||"?",e=arguments.callee;e.hasOwnProperty[f]||(e[f]={});e=e[f];
if(e.hasOwnProperty(g))return e[g];var h={},d=g.indexOf(f),i=g.substring(d+1).split("&");if(-1!==d)for(var d=0,c=i.length;d<c;d++){var a=i[d].split("="),b=decodeURIComponent(a[0]),a=decodeURIComponent(a[1]);h.hasOwnProperty(b)?(h[b].constructor!==Array&&(h[b]=[h[b]]),h[b].push(a)):h[b]=a}return e[g]=h}}});
H&&H("union/common/cookie1426591083",[],function(){return{V:function(g,f){var e,h=RegExp("(^| )"+g+"=([^;]*)(;|$)").exec((f||window).document.cookie);h&&(e=h[2]);return e},ga:function(g,f,e){var e=e||{},h=e.aa;"number"==typeof e.aa&&(h=new Date,h.setTime(h.getTime()+e.aa));document.cookie=""+g+"="+f+(e.path?"; path="+e.path:"")+(h?"; expires="+h.toGMTString():"")+(e.domain?"; domain="+e.domain:"")+(e.kd?"; secure":"")},remove:function(g){var f=new Date;f.setTime(f.getTime()-86400);this.ga(g,"",{path:"/",aa:f})}}});
H&&H("union/preview1426591083",["union/common/bom1426591083","union/common/logic1426591083","union/common/cookie1426591083"],function(g,f,e){function h(d){d=decodeURIComponent(d).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return f.vc(d)}function d(d,c){var a;a=c?c.substring(c.indexOf("?")):g.Da(window)?window.location.search.slice(1):window.top.location.search.slice(1);var b=document.referrer,j=0<=d.indexOf("inlay")||"ui"===d?"bd_cpro_prev":"bd_cpro_fprev",k="",q;try{q=document.cookie}catch(o){}-1!==
a.indexOf(j)&&(k=f.Bb(a,j));!k&&q&&-1!==q.indexOf(j)&&(k=e.V(j));!k&&-1!==b.indexOf(j)&&(k=f.Bb(b,j));return k}return{Za:function(e,c){var a=window.location.href,b=parseInt(e.rsi0,10),j=parseInt(e.rsi1,10),k=parseInt(e.at,10),q=u,o=d(c,a);if(o)if(o=h(o),k===l&&(k=1),1!==parseInt(o.type,10)&&2===(k&2))q=parseInt(o.imgWidth,10)===parseInt(b,10)&&parseInt(o.imgHeight,10)===parseInt(j,10);else if(1===parseInt(o.type,10)&&(1===(k&1)||64===(k&64)||32===(k&32)))q=n;return q?(b=0<=c.indexOf("inlay")||"ui"===
c?"bd_cpro_prev":"bd_cpro_fprev",a=d(c,a),j=e.tn,k=h(a),q=s,0<=c.indexOf("inlay")?q={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(k.type,10)?j+".html":2===parseInt(k.type,10)?"image.html":4===parseInt(k.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+b+"=#"+a+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:"float"===c&&(k=parseInt(k.type,10),k="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===k?"float_image.html":4===k?"float_flash.html":"blank_tips.html")+
"?",a="tn="+j+("&"+b+"="+a).replace(/\./g,"%252e")+"&ut="+ +new Date,q={serviceUrl:k,paramString:a}),q):s}}});
H&&H("union/common/oo1426591083",[],function(){function g(d){var e=g.create(g);return d.call(e,e,e.sb)}function f(d,e){if(d.constructor===Array)for(var c=0,a=d.length;c<a;c++){if(e.call(d,d[c],c,d)===u)return u}else{var c=!{toString:1}.propertyIsEnumerable("toString"),b="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(a in d)if(d.hasOwnProperty(a)&&e.call(d,d[a],a,d)===u)return u;if(c){c=0;for(a=b.length;c<a;c++){var f=b[c];if(d.hasOwnProperty(f)&&
e.call(d,f,c,d)===u)return u}}}return n}function e(d,e,c){f(e,function(a,b){if(!d.hasOwnProperty(b)||c)d[b]=a})}function h(d){function e(){}if(Object.create)return Object.create(d);e.prototype=d;return new e}g.sb={};g.create=h;g.ac=f;g.Ma=function(d){var f,c=d.hasOwnProperty("constructor")?d.constructor:function(){};c.prototype=d;c.prototype.constructor=c;f=f||{};f.kb&&e(c,f.kb);return c};g.extend=function(d,f,c){var a;a=f.hasOwnProperty("constructor")?f.constructor:function(){d.constructor.apply(this,
arguments)};a.prototype=h(d.prototype);e(a.prototype,f,n);a.prototype.constructor=a;a.prototype.Pc=d.prototype;e(a,d);c=c||{};c.kb&&e(a,c.kb,n);return a};g.fd=function(d){var e=this.sb;f(d.split("."),function(c){e.hasOwnProperty(c)||(e[c]={});e=e[c]});return e};g.i=function(d,e){var c;return function(){c=c||[];for(var a=0,b=arguments.length;a<b;a++)c.push(arguments[a]);return d.apply(e||{},c)}};return g});
H&&H("union/common/dom1426591083",["union/common/oo1426591083","union/common/bom1426591083"],function(g,f){return g(function(e){var g=f.h;return{m:function(d,e){return"string"===typeof d||d instanceof String?(e||window).document.getElementById(d):d},Cb:function(d,i){var c=n;if("string"===typeof i)return d.id===i;if(i.constructor===Object)return e.ac(i,function(a,b){var e=(d.getAttribute?d.getAttribute(b):d[b])||d[b];if("tagName"===b){if(e.toUpperCase()!=a.toUpperCase())return c=u}else if(e!=a)return c=u}),c;if(i.constructor===
Array){var a=i.concat([]);a.reverse();for(var b=d;b&&a.length;b=b.parentNode)this.Cb(b,a[0])&&a.shift();return!a.length?n:u}},Nb:function(d,e){if(d&&e(d)!==u){var c=d.childNodes;if(c)for(var a=0,b=c.length;a<b;a++)if(this.Nb(c[a],e)===u)return u}},Kb:function(d,e){var c=this;d.constructor===Object&&(d=this.r(d));if("string"===typeof e){for(var a=document.getElementById(e),b=a;b;){if(b===d)return a;b=b.parentNode}return s}if(e.constructor===Object){var f=s;c.Nb(d,function(a){if(c.Cb(a,e))return f=
a,u});return f}},r:function(d){if(d){if(d.nodeName)return d;1<arguments.length&&(d=Array.prototype.slice.call(arguments,0));if("string"===typeof d)return document.getElementById(d);if(d.constructor===Object)return this.Kb(document.documentElement,d);if(d.constructor===Array){for(var e=d.concat([]),c=document.documentElement;e.length&&c;)c=this.Kb(c,e.shift());return c}}},Bc:function(d,i,c){var c=c||this.od||window,a=c.document;this.wb=0;this.da=this.da||[];this.da.push({Xa:d,vb:i||0,Ta:u});var b=
e.i(function(){var b=u;this.wb++;var d=u;try{c.frameElement&&(d=n)}catch(e){d=n}if(g.g&&9>g.g&&!d)try{a.documentElement.doScroll("left"),b=n}catch(i){}else if("complete"===a.readyState||this.$b)b=n;else if(3E5<this.wb){this.U&&(c.clearInterval(this.U),this.U=s);return}if(b)try{if(this.da&&this.da.length)for(var b=0,f=this.da.length;b<f;b++){var v=this.da[b];v&&v.Xa&&!v.Ta&&(v.vb?(v.Ta=n,c.setTimeout(v.Xa,v.vb)):(v.Ta=n,v.Xa()))}}catch(w){throw w;}finally{this.U&&(c.clearInterval(this.U),this.U=s)}},
this),d=e.i(function(){this.$b=n;b()},this);this.U||(this.U=c.setInterval(b,50),a.addEventListener?(a.addEventListener("DOMContentLoaded",d,u),c.addEventListener("load",d,u)):a.attachEvent&&c.attachEvent("onload",d,u))},A:function(){var d=n;if(g.g&&(7>g.g||"BackCompat"===document.compatMode))d=u;return d},bind:function(d,e,c){"string"===typeof d&&(d=this.r(d));e=e.replace(/^on/i,"").toLowerCase();d.addEventListener?d.addEventListener(e,c,u):d.attachEvent&&d.attachEvent("on"+e,c);return d},Ob:function(d,
e,c){d=this.r(d);if(!d)return s;e=e.replace(/^on/i,"").toLowerCase();d.removeEventListener?d.removeEventListener(e,c,u):d.detachEvent&&d.detachEvent("on"+e,c);return d},t:function(d,e){var c;"string"===typeof d&&(d=this.r(d));var a=f.Ya(d),b="",b=-1<e.indexOf("-")?e.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):e.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});a&&a.defaultView&&a.defaultView.getComputedStyle?((a=a.defaultView.getComputedStyle(d,s))&&
(c=a.getPropertyValue(e)),"boolean"!==typeof c&&!c&&(c=a.getPropertyValue(b))):d.currentStyle&&((a=d.currentStyle)&&(c=a[e]),"boolean"!==typeof c&&!c&&(c=a[b]));return c},nc:function(d,e){e=e||window;"string"===typeof d&&(d=this.r(d));if(d){for(var c=this.ca(d),a,b=0;e!=e.parent&&10>b;)b++,a=this.ca(e.frameElement),c.left+=a.left,c.top+=a.top,e=e.parent;return c}},ca:function(d){"string"===typeof d&&(d=this.r(d));var e=f.Ya(d),c=f.h;0<c.sc&&e.getBoxObjectFor&&this.t(d,"position");var a={left:0,top:0},
b;if(d==(c.g&&!c.Db?e.body:e.documentElement)||!d)return a;if(d.getBoundingClientRect)d=d.getBoundingClientRect(),a.left=Math.floor(d.left)+Math.max(e.documentElement.scrollLeft,e.body.scrollLeft),a.top=Math.floor(d.top)+Math.max(e.documentElement.scrollTop,e.body.scrollTop),a.left-=e.documentElement.clientLeft,a.top-=e.documentElement.clientTop,d=e.body,e=parseInt(this.t(d,"borderLeftWidth"),10),d=parseInt(this.t(d,"borderTopWidth"),10),c.g&&!c.Db&&(a.left-=isNaN(e)?2:e,a.top-=isNaN(d)?2:d);else{b=
d;do{a.left+=b.offsetLeft;a.top+=b.offsetTop;if(0<c.Eb&&"fixed"==this.t(b,"position")){a.left+=e.body.scrollLeft;a.top+=e.body.scrollTop;break}b=b.offsetParent}while(b&&b!=d);if(0<c.opera||0<c.Eb&&"absolute"==this.t(d,"position"))a.top-=e.body.offsetTop;for(b=d.offsetParent;b&&b!=e.body;){a.left-=b.scrollLeft;if(!c.opera||"TR"!=b.tagName)a.top-=b.scrollTop;b=b.offsetParent}}return a},Ab:function(d,e){var d=this.r(d),c=d.offsetWidth;if(e||u)var a=this.t(d,"marginLeft").toString().toLowerCase().replace("px",
"").replace("auto","0"),b=this.t(d,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),c=c+(parseInt(a||0,10)+parseInt(b||0,10));return c},zb:function(d,e){var d=this.r(d),c=d.offsetHeight;if(e||u)var a=this.t(d,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),b=this.t(d,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),c=c+(parseInt(a||0,10)+parseInt(b||0,10));return c},$c:function(d){var d=this.r(d),e=this.ab(d),c=0;
if(this.pa(window)&&!f.Da(window)){for(;e.parent!=window.top&&10>c;)c++,e=e.parent;10>c&&(d=e.frameElement||d)}return d},yb:function(d){var e=this.r(d),d=this.ab(e),c=100,a;try{for(;e&&e.tagName;){a=100;if(this.h.g){if(5<this.h.g)try{a=e.Vc.alpha.opacity||100}catch(b){}c=c>a?a:c}else{try{a=100*(d.getComputedStyle(e,s).opacity||1)}catch(f){}c*=a/100}e=e.parentNode}}catch(g){}return c||100},Xc:function(d){for(var e=this.r(d),d=this.ab(e),e=this.yb(e),c=100,a=0;this.pa(d);){a++;if(f.Da(d,d.parent))break;
else c=100,d.frameElement&&(c=this.yb(d.frameElement)),e*=c/100;d=d.parent}return e}}})});
H&&H("union/business/businessLogic1426591083",["union/preview1426591083","union/common/dom1426591083","api"],function(g,f,e){var h={inlay:8,"float":2,patch:2,linkunit:20,popup:1},d={inlay:{},"float":{},patch:{},linkunit:{},popup:{}},i={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{ra:function(c){var a=
c._html||{},b="",d="http://cb.baidu.com/ecom?",f=c.id.split("_")[0],h=parseInt(a.conW||0,10)||parseInt(c._w,10)||parseInt(c.sw,10)||parseInt(a.rsi0,10),i=parseInt(a.conH||0,10)||parseInt(c._h,10)||parseInt(c.sh,10)||parseInt(a.rsi1,10),C=c.displayType,v=a.tn||"",w=v.toLowerCase(),z=a.ch||0,m=c.qn||"",r=a.n||"",t=a.dai||0;a.dtm="BAIDU_DUP2_SETJSONADSLOT";a.dc="2";a.di=f;e.getInfo("ssp_beta_"+c.id)===n&&(a.ssp=8);(b=e.getInfo("timestampWathcer"+c.id))&&(a.tt=b.t1+"."+(b.t2-b.t1)+"."+(b.t3-b.t1)+"."+
(+new Date-b.t1));var b=[],p;for(p in a)p&&a.hasOwnProperty(p)&&b.push(""+p+"="+encodeURIComponent(a[p].toString()));b=b.join("&");if((p=g.Za(a,C))&&p.serviceUrl!==l&&p.paramString!==l)d=p.serviceUrl,b=p.paramString;return{slotId:f,slotWidth:h,slotHeight:i,displayType:C,styleType:w,iframeId:"cproIframe_"+f+"_"+a.dai,unionAccount:r,adIndex:t,channel:z,pvId:m,stuffType:"unknown",serviceUrl:d,paramString:b,delayIn:a.delayIn,delayOut:a.delayOut,sessionSync:a.sessionSync!==u&&"false"!==a.sessionSync,closeFor:a.closeFor,
xuantingType:a.xuanting,tn:v}},hb:function(c){var a={};a.Zb=(c.Zb||"pc").toLowerCase();a.B=(c.B||"inlay-fixed").toLowerCase();a.s=(c.s||"template_inlay_all_normal").toLowerCase();a.N=(c.N||"text").toLowerCase();a.K=c.K;if(-1<a.s.indexOf("tlink")||-1<a.s.indexOf("linkunit"))a.B="linkunit-fixed";0<=a.s.indexOf("float_xuanfuwin")&&(a.B="popup-float");c=a.B.split("-");a.Sa=c[0]||"inlay";a.Tc=c[1]||"fixed";return a},la:function(c){var c=this.hb(c),a=c.Sa;return this.fc(c)<h[a]},fc:function(c){var c=this.hb(c),
a=0,c=d[c.Sa],b;for(b in c)b&&c[b]&&c.hasOwnProperty(b)&&(f.m(b)?a++:c[b]=l);return a},ta:function(c){c=this.hb(c);d[c.Sa][c.K]=1;return n},Ba:function(c,a){var b=document.getElementById("cpro_"+c);b||(b=document.getElementById(a));return b},hc:function(c){return i[c]},Ha:function(c){var a=c.slotId;E(["viewWatch"],function(b){b.register({id:a,wrapperId:c.iframeId,logType:"block",extra:"ch="+c.channel+"&jk="+c.pvId+"&n="+c.unionAccount})},n)}}});H&&H("union/inlayFixed",["union/business/businessLogic1426591083"],function(g){function f(e){return'<iframe id="{iframeId}" width="{slotWidth}" height="{slotHeight}" src="{serviceUrl}{paramString}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true"></iframe>'.replace(/{(.*?)}/g,function(f,d){return e[d]||""})}return{render:function(e,h){e.displayType="inlay-fixed";var d=g.ra(e),i=g.Ba(d.slotId,h),c={B:d.displayType,s:d.styleType,N:d.stuffType,K:d.iframeId};
if(!g.la(c))return u;i.innerHTML=f(d);g.ta(c);g.Ha(d,h)}}});
})();
